<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>africa</string>
		<string>antarctica</string>
		<string>asia</string>
		<string>australasia</string>
		<string>backward</string>
		<string>backzone</string>
		<string>etcetera</string>
		<string>europe</string>
		<string>factory</string>
		<string>leapseconds</string>
		<string>northamerica</string>
		<string>pacificnew</string>
		<string>southamerica</string>
		<string>systemv</string>
		<string>iso3166.tab</string>
		<string>leap-seconds.list</string>
		<string>zone.tab</string>
		<string>zone1970.tab</string>
	</array>
	<key>name</key>
	<string>zoneinfo</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Line comments</string>
			<key>name</key>
			<string>comment.line.number-sign.zoneinfo</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.zone.zoneinfo</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.zone.zoneinfo</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.time.zoneinfo</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.rule.zoneinfo</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>variable.other.format.zoneinfo</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Zone definitions</string>
			<key>match</key>
			<string>(?x)               # (extended format for regexp)
^(Zone)?           # "Zone"
\s+([\w+\-\/]+)?   # Zone name
\s+([\d:\-]+)      # UTC offset
\s+([\w:\-]+)      # Rules
\s+([\w%+\-\/]+)?  # Format
</string>
			<key>name</key>
			<string>meta.zone.zoneinfo</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(Rule)\s+([\w:\-]+)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.rule.zoneinfo</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.rule.zoneinfo</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Rule defintions</string>
			<key>end</key>
			<string>\s([A-Za-z]+)?(\s*(\#.*))?$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.format.zoneinfo</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>comment.line.number-sign.zoneinfo</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.rule.zoneinfo</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#time</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#year</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(Link)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.link.zoneinfo</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Link definitions</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.link.zoneinfo</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#zonename_loose</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(Leap)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.leap.zoneinfo</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Leap second definitions</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.leap.zoneinfo</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#time</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#year</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^([A-Z]{2})\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.country.zoneinfo</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>zone.tab lines</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.zonetab.zoneinfo</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#isocountry</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#latlng</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#zonename</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Time values</string>
			<key>name</key>
			<string>constant.numeric.time.zoneinfo</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#time</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>Year values</string>
			<key>name</key>
			<string>constant.numeric.year.zoneinfo</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#year</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>begin</key>
			<string>\#</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.line.number-sign.zoneinfo</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#url</string>
				</dict>
			</array>
		</dict>
		<key>date</key>
		<dict>
			<key>match</key>
			<string>\b\d{4}(-\d{2}){2}\b</string>
			<key>name</key>
			<string>constant.numeric.date.zoneinfo</string>
		</dict>
		<key>isocountry</key>
		<dict>
			<key>match</key>
			<string>\b[A-Z]{2}\b</string>
			<key>name</key>
			<string>variable.other.country.zoneinfo</string>
		</dict>
		<key>latlng</key>
		<dict>
			<key>match</key>
			<string>([+\-]\d{4,}){2}</string>
			<key>name</key>
			<string>constant.numeric.latlng.zoneinfo</string>
		</dict>
		<key>time</key>
		<dict>
			<key>match</key>
			<string>-?\d+(:\d+)+|\b0\b</string>
			<key>name</key>
			<string>constant.numeric.time.zoneinfo</string>
		</dict>
		<key>url</key>
		<dict>
			<key>match</key>
			<string>\b[A-Za-z]+:\/\/\S+?\.\S+?(?=[&gt;\s\]])</string>
			<key>name</key>
			<string>string.other.link.zoneinfo</string>
		</dict>
		<key>year</key>
		<dict>
			<key>match</key>
			<string>\b\d{4}\b</string>
			<key>name</key>
			<string>constant.numeric.year.zoneinfo</string>
		</dict>
		<key>zonename</key>
		<dict>
			<key>match</key>
			<string>\b[\w+\-]+(\/[\w+\-]+)+\b</string>
			<key>name</key>
			<string>entity.name.zone.zoneinfo</string>
		</dict>
		<key>zonename_loose</key>
		<dict>
			<key>match</key>
			<string>\b[\w+\-\/]+\b</string>
			<key>name</key>
			<string>entity.name.zone.zoneinfo</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.zoneinfo</string>
	<key>uuid</key>
	<string>6f25ec5b-a532-479a-841d-596ff7c820b3</string>
</dict>
</plist>
